import type { TableDefinitionDTO } from '@shared/contracts/platform/registry';
import {
  createStaticTableRegistryRepository,
  type TableRegistryRepository,
} from '../../../repositories/platform/table-registry-repository';

export type HeaderMap = Record<string, number>;

export type MigrationPlan =
  | {
      action: 'none';
      missingHeaders: readonly string[];
    }
  | {
      action: 'createTable' | 'appendColumns';
      missingHeaders: readonly string[];
    };

export interface TableRegistryService {
  getDefinitions(): readonly TableDefinitionDTO[];
  createHeaderMap(tableName: string, actualHeaders: readonly string[]): HeaderMap;
  planMigration(tableName: string, actualHeaders: readonly string[]): MigrationPlan;
}

export function createTableRegistryService(repository: TableRegistryRepository): TableRegistryService {
  return {
    getDefinitions() {
      return repository.listDefinitions();
    },
    createHeaderMap(_tableName, actualHeaders) {
      return Object.fromEntries(actualHeaders.map((header, index) => [header, index]));
    },
    planMigration(tableName, actualHeaders) {
      const definition = findDefinition(repository, tableName);
      const missingHeaders = definition.headers
        .map((header) => header.name)
        .filter((header) => !actualHeaders.includes(header));

      if (actualHeaders.length === 0) {
        return { action: 'createTable', missingHeaders };
      }

      if (missingHeaders.length > 0) {
        return { action: 'appendColumns', missingHeaders };
      }

      return { action: 'none', missingHeaders: [] };
    },
  };
}

export function createTableRegistryServiceForTest(): TableRegistryService {
  return createTableRegistryService(createStaticTableRegistryRepository(createPlatformTableDefinitions()));
}

export function createPlatformTableDefinitions(): readonly TableDefinitionDTO[] {
  return [
    table('CommandTransaction', 'transaction', 'ledger', 'transaction-period', [
      'id',
      'commandId',
      'idempotencyKey',
      'status',
      'createdAt',
      'updatedAt',
      'resultJson',
    ]),
    table('AuditOutbox', 'transaction', 'audit', 'transaction-period', [
      'id',
      'eventId',
      'commandId',
      'actorId',
      'action',
      'status',
      'createdAt',
    ]),
    table('Session', 'runtime', 'runtime', 'none', [
      'id',
      'tokenFingerprint',
      'userId',
      'authVersion',
      'issuedAt',
      'idleExpiresAt',
      'absoluteExpiresAt',
      'revokedAt',
    ]),
    table('UserAccount', 'core', 'master', 'none', [
      'id',
      'loginId',
      'displayName',
      'tenantId',
      'authVersion',
      'disabled',
      'passwordChangeRequired',
    ]),
    table('RolePermission', 'core', 'master', 'none', ['id', 'roleId', 'action', 'tenantId']),
    table('UserScope', 'core', 'master', 'none', [
      'id',
      'userId',
      'tenantId',
      'branchId',
      'warehouseId',
    ]),
    table('SchemaMigration', 'core', 'runtime', 'none', [
      'id',
      'migrationId',
      'tableName',
      'fromVersion',
      'toVersion',
      'status',
      'createdAt',
    ]),
    table('PartitionRegistry', 'core', 'runtime', 'none', [
      'id',
      'storageRole',
      'partitionKey',
      'spreadsheetId',
      'status',
      'activeFrom',
      'closedAt',
    ]),
    table('ImportBatch', 'runtime', 'runtime', 'none', [
      'batchId',
      'importType',
      'schemaVersion',
      'actorId',
      'scopeKey',
      'status',
      'rowCount',
      'validCount',
      'invalidCount',
      'selectionMode',
      'committedAt',
    ], 'operations'),
    table('ImportStagingRow', 'runtime', 'runtime', 'none', [
      'stagingRowId',
      'batchId',
      'rowNumber',
      'rowKey',
      'validationStatus',
      'errorCount',
      'commitStatus',
      'sourceObjectId',
    ], 'operations'),
    table('ExportRun', 'runtime', 'runtime', 'none', [
      'exportRunId',
      'reportId',
      'actorId',
      'scopeFingerprint',
      'status',
      'requestedAt',
      'startedAt',
      'completedAt',
      'expiresAt',
      'fileId',
      'rowCount',
      'runId',
    ], 'operations'),
    table('BackgroundRun', 'runtime', 'runtime', 'none', [
      'runId',
      'jobType',
      'status',
      'attempt',
      'leaseUntil',
      'checkpointKey',
      'startedAt',
      'endedAt',
      'errorCode',
    ], 'operations'),
    table('HealthCheck', 'runtime', 'runtime', 'none', [
      'checkId',
      'checkType',
      'status',
      'observedAt',
      'resourceKey',
      'threshold',
      'observedValue',
      'acknowledgedAt',
    ], 'operations'),
    table('CapacityAlert', 'runtime', 'runtime', 'none', [
      'alertId',
      'alertType',
      'status',
      'observedAt',
      'resourceKey',
      'threshold',
      'observedValue',
      'acknowledgedAt',
    ], 'operations'),
    table('AttachmentMetadata', 'transaction', 'document', 'transaction-period', [
      'attachmentId',
      'partitionKey',
      'objectType',
      'objectId',
      'branchId',
      'warehouseId',
      'driveFileId',
      'fileName',
      'mimeType',
      'sizeBytes',
      'checksum',
      'status',
      'uploadedBy',
      'deletedAt',
    ], 'operations'),
    table('AuditLog', 'audit', 'audit', 'audit-period', [
      'eventId',
      'auditPartitionKey',
      'action',
      'objectType',
      'objectId',
      'actorId',
      'branchId',
      'warehouseId',
      'occurredAt',
      'result',
    ], 'operations'),
    table('BackupRun', 'transaction', 'document', 'transaction-period', [
      'backupRunId',
      'status',
      'requestedBy',
      'startedAt',
      'completedAt',
      'manifestFileId',
      'appVersion',
      'schemaVersion',
      'checksum',
      'retentionUntil',
    ], 'operations'),
    table('RestoreRun', 'transaction', 'document', 'transaction-period', [
      'restoreRunId',
      'backupRunId',
      'status',
      'requestedBy',
      'preparedAt',
      'switchedAt',
      'oldConfigVersion',
      'newConfigVersion',
      'healthResult',
    ], 'operations'),
    table('ReportProjectionState', 'transaction', 'projection', 'transaction-period', [
      'projectionId',
      'reportId',
      'branchId',
      'warehouseId',
      'dateBucket',
      'asOf',
      'sourcePartitionKey',
      'buildVersion',
      'status',
    ], 'reporting'),
    table('Product', 'core', 'master', 'none', [
      'productId',
      'productCode',
      'name',
      'productType',
      'categoryId',
      'brandId',
      'taxCode',
      'isActive',
      'descriptionJson',
    ], 'catalog'),
    table('Variant', 'core', 'master', 'none', [
      'variantId',
      'productId',
      'skuNormalized',
      'displayName',
      'inventoryMode',
      'lotTracking',
      'serialTracking',
      'defaultUnitId',
      'isActive',
    ], 'catalog'),
    table('VariantBarcode', 'core', 'master', 'none', [
      'barcodeId',
      'variantId',
      'unitVersionId',
      'barcodeNormalized',
      'barcodeKind',
      'isActive',
    ], 'catalog'),
    table('UnitConversionVersion', 'core', 'master', 'none', [
      'unitVersionId',
      'variantId',
      'unitId',
      'baseUnitId',
      'factor',
      'saleEnabled',
      'purchaseEnabled',
      'effectiveFrom',
      'effectiveTo',
      'isActive',
    ], 'catalog'),
    table('PriceList', 'core', 'master', 'none', [
      'priceListId',
      'name',
      'scopeType',
      'branchId',
      'customerGroupId',
      'status',
      'effectiveFrom',
      'effectiveTo',
      'priority',
    ], 'catalog'),
    table('PriceRule', 'core', 'master', 'none', [
      'priceRuleId',
      'priceListId',
      'variantId',
      'unitVersionId',
      'unitPriceVnd',
      'effectiveFrom',
      'effectiveTo',
      'priority',
      'status',
    ], 'catalog'),
    table('Promotion', 'core', 'master', 'none', [
      'promotionId',
      'name',
      'promotionType',
      'status',
      'branchScopeKey',
      'effectiveFrom',
      'effectiveTo',
      'priority',
      'usageLimit',
      'budgetVnd',
      'detailsJson',
    ], 'catalog'),
    table('Voucher', 'core', 'master', 'none', [
      'voucherId',
      'promotionId',
      'codeNormalized',
      'status',
      'effectiveFrom',
      'effectiveTo',
      'usageLimit',
      'usedCount',
      'detailsJson',
    ], 'catalog'),
    table('Customer', 'core', 'master', 'none', [
      'customerId',
      'customerCode',
      'displayName',
      'phoneNormalized',
      'emailNormalized',
      'customerGroupId',
      'status',
      'mergedIntoCustomerId',
      'detailsJson',
    ], 'crm'),
    table('CustomerGroup', 'core', 'master', 'none', [
      'customerGroupId',
      'name',
      'assignmentMode',
      'status',
      'priority',
      'detailsJson',
    ], 'crm'),
    table('SaleOrder', 'transaction', 'document', 'transaction-period', [
      'saleOrderId',
      'partitionKey',
      'businessNumber',
      'source',
      'branchId',
      'warehouseId',
      'status',
      'paymentStatus',
      'customerId',
      'cashierId',
      'subtotalVnd',
      'discountVnd',
      'taxVnd',
      'shippingFeeVnd',
      'totalVnd',
      'paidVnd',
      'receivableVnd',
      'quoteVersion',
      'createdAt',
      'completedAt',
      'cancelledAt',
      'snapshotJson',
    ], 'sales'),
    table('SaleOrderLine', 'transaction', 'document', 'transaction-period', [
      'saleOrderLineId',
      'saleOrderId',
      'variantId',
      'unitVersionId',
      'quantityMilli',
      'unitPriceVnd',
      'lineDiscountVnd',
      'lineTotalVnd',
      'lotId',
      'serialId',
      'snapshotJson',
    ], 'sales'),
    table('SaleTenderDraft', 'transaction', 'document', 'transaction-period', [
      'tenderDraftId',
      'saleOrderId',
      'methodId',
      'amountVnd',
      'cashDrawerId',
      'snapshotJson',
    ], 'sales'),
    table('ReceiptSnapshot', 'transaction', 'document', 'transaction-period', [
      'receiptId',
      'saleOrderId',
      'businessNumber',
      'renderVersion',
      'createdAt',
      'snapshotJson',
    ], 'sales'),
    table('InventoryMovement', 'transaction', 'ledger', 'transaction-period', [
      'movementId',
      'partitionKey',
      'movementType',
      'warehouseId',
      'variantId',
      'lotId',
      'serialId',
      'quantityMilli',
      'unitVersionId',
      'unitCostVnd',
      'totalCostVnd',
      'sourceType',
      'sourceId',
      'effectiveAt',
      'reversalOfMovementId',
      'snapshotJson',
    ], 'inventory'),
    table('InventoryBalance', 'transaction', 'projection', 'none', [
      'balanceId',
      'warehouseId',
      'variantId',
      'onHandMilli',
      'availableMilli',
      'reservedMilli',
      'inTransitMilli',
      'quarantineMilli',
      'inventoryValueVnd',
      'asOfMovementId',
      'reconciliationJson',
    ], 'inventory'),
    table('InventoryLotBalance', 'transaction', 'projection', 'none', [
      'lotBalanceId',
      'warehouseId',
      'variantId',
      'lotCode',
      'expiryDate',
      'onHandMilli',
      'availableMilli',
      'quarantineMilli',
      'metadataJson',
    ], 'inventory'),
    table('SerialState', 'transaction', 'projection', 'none', [
      'serialId',
      'variantId',
      'warehouseId',
      'status',
      'sourceMovementId',
      'sourceSaleLineId',
      'updatedAt',
      'historyJson',
    ], 'inventory'),
    table('StockTransfer', 'transaction', 'document', 'transaction-period', [
      'transferId',
      'sourceWarehouseId',
      'destinationWarehouseId',
      'status',
      'createdAt',
      'approvedAt',
      'shippedAt',
      'receivedAt',
      'reasonJson',
    ], 'inventory'),
    table('StockTransferLine', 'transaction', 'document', 'transaction-period', [
      'transferLineId',
      'transferId',
      'variantId',
      'quantityMilli',
      'receivedQuantityMilli',
      'varianceJson',
    ], 'inventory'),
    table('StocktakeSession', 'transaction', 'document', 'transaction-period', [
      'sessionId',
      'warehouseId',
      'status',
      'snapshotAt',
      'submittedAt',
      'approvedAt',
      'scopeJson',
    ], 'inventory'),
    table('StocktakeLine', 'transaction', 'document', 'transaction-period', [
      'stocktakeLineId',
      'sessionId',
      'variantId',
      'lotId',
      'serialId',
      'snapshotQuantityMilli',
      'countedQuantityMilli',
      'varianceMilli',
      'reasonJson',
    ], 'inventory'),
    table('CashDrawer', 'core', 'master', 'none', [
      'cashDrawerId',
      'branchId',
      'drawerCode',
      'name',
      'drawerType',
      'status',
      'configJson',
    ], 'finance'),
    table('PaymentMethod', 'core', 'master', 'none', [
      'paymentMethodId',
      'methodCode',
      'name',
      'methodType',
      'status',
      'configJson',
    ], 'finance'),
    table('Payment', 'transaction', 'document', 'transaction-period', [
      'paymentId',
      'partitionKey',
      'branchId',
      'payerType',
      'payerId',
      'sourceType',
      'sourceId',
      'amountVnd',
      'paymentMethodId',
      'status',
      'effectiveAt',
      'shiftId',
      'reversalOfPaymentId',
      'snapshotJson',
    ], 'finance'),
    table('CashTransaction', 'transaction', 'ledger', 'transaction-period', [
      'cashTransactionId',
      'partitionKey',
      'branchId',
      'cashDrawerId',
      'transactionType',
      'amountVnd',
      'effectiveAt',
      'paymentId',
      'sourceType',
      'sourceId',
      'actorId',
      'approverId',
      'shiftId',
      'reversalOfCashTransactionId',
      'reasonJson',
    ], 'finance'),
    table('ReceivableLedger', 'transaction', 'ledger', 'transaction-period', [
      'obligationId',
      'partitionKey',
      'branchId',
      'customerId',
      'sourceType',
      'sourceId',
      'dueDate',
      'originalAmountVnd',
      'allocatedAmountVnd',
      'remainingAmountVnd',
      'status',
      'reversalOfObligationId',
      'termsJson',
    ], 'finance'),
    table('PayableLedger', 'transaction', 'ledger', 'transaction-period', [
      'obligationId',
      'partitionKey',
      'branchId',
      'supplierId',
      'sourceType',
      'sourceId',
      'dueDate',
      'originalAmountVnd',
      'allocatedAmountVnd',
      'remainingAmountVnd',
      'status',
      'reversalOfObligationId',
      'termsJson',
    ], 'finance'),
    table('PaymentAllocation', 'transaction', 'ledger', 'transaction-period', [
      'allocationId',
      'partitionKey',
      'paymentId',
      'obligationId',
      'amountVnd',
      'allocatedAt',
      'reversalOfAllocationId',
      'reasonJson',
    ], 'finance'),
    table('CustomerCredit', 'transaction', 'ledger', 'transaction-period', [
      'creditId',
      'partitionKey',
      'branchId',
      'customerId',
      'sourcePaymentId',
      'amountVnd',
      'consumedAmountVnd',
      'status',
      'snapshotJson',
    ], 'finance'),
    table('SupplierPrepayment', 'transaction', 'ledger', 'transaction-period', [
      'prepaymentId',
      'partitionKey',
      'branchId',
      'supplierId',
      'sourcePaymentId',
      'amountVnd',
      'consumedAmountVnd',
      'status',
      'snapshotJson',
    ], 'finance'),
    table('Shift', 'transaction', 'document', 'transaction-period', [
      'shiftId',
      'partitionKey',
      'branchId',
      'cashDrawerId',
      'warehouseId',
      'cashierId',
      'status',
      'openedAt',
      'submittedAt',
      'closedAt',
      'lockedAt',
      'openingCashVnd',
      'expectedCashVnd',
      'actualCashVnd',
      'varianceVnd',
      'approverId',
      'breakdownJson',
    ], 'finance'),
    table('Expense', 'transaction', 'document', 'transaction-period', [
      'expenseId',
      'partitionKey',
      'branchId',
      'categoryId',
      'cashDrawerId',
      'payee',
      'amountVnd',
      'effectiveAt',
      'status',
      'cashTransactionId',
      'actorId',
      'approverId',
      'attachmentJson',
    ], 'finance'),
  ];
}

function table(
  tableName: string,
  storageRole: TableDefinitionDTO['storageRole'],
  lifecycle: TableDefinitionDTO['lifecycle'],
  partitionPolicy: TableDefinitionDTO['partitionPolicy'],
  headers: readonly string[],
  owner: TableDefinitionDTO['owner'] = 'platform',
): TableDefinitionDTO {
  return {
    tableName,
    owner,
    storageRole,
    sheetName: tableName,
    lifecycle,
    schemaVersion: 1,
    primaryKey: 'id',
    headers: headers.map((name) => ({
      name,
      type: name.endsWith('Json') ? 'json' : name.endsWith('At') ? 'timestamp' : 'string',
      required: name !== 'revokedAt' && name !== 'closedAt' && name !== 'resultJson',
    })),
    partitionPolicy,
    lookupKeys: [{ name: `${tableName}.primary`, columns: ['id'], unique: true }],
  };
}

function findDefinition(
  repository: TableRegistryRepository,
  tableName: string,
): TableDefinitionDTO {
  const definition = repository.listDefinitions().find((candidate) => candidate.tableName === tableName);

  if (definition === undefined) {
    throw new Error(`Unknown table: ${tableName}`);
  }

  return definition;
}
