import type { TableDefinitionDTO } from '@shared/contracts/platform/registry';
import {
  createStaticTableRegistryRepository,
  type TableRegistryRepository,
} from '../../../repositories/platform/table-registry-repository';

export type HeaderMap = Record<string, number>;

export type MigrationPlan =
  | {
      action: 'none';
      missingHeaders: readonly string[];
    }
  | {
      action: 'createTable' | 'appendColumns';
      missingHeaders: readonly string[];
    };

export interface TableRegistryService {
  getDefinitions(): readonly TableDefinitionDTO[];
  createHeaderMap(tableName: string, actualHeaders: readonly string[]): HeaderMap;
  planMigration(tableName: string, actualHeaders: readonly string[]): MigrationPlan;
}

export function createTableRegistryService(repository: TableRegistryRepository): TableRegistryService {
  return {
    getDefinitions() {
      return repository.listDefinitions();
    },
    createHeaderMap(_tableName, actualHeaders) {
      return Object.fromEntries(actualHeaders.map((header, index) => [header, index]));
    },
    planMigration(tableName, actualHeaders) {
      const definition = findDefinition(repository, tableName);
      const missingHeaders = definition.headers
        .map((header) => header.name)
        .filter((header) => !actualHeaders.includes(header));

      if (actualHeaders.length === 0) {
        return { action: 'createTable', missingHeaders };
      }

      if (missingHeaders.length > 0) {
        return { action: 'appendColumns', missingHeaders };
      }

      return { action: 'none', missingHeaders: [] };
    },
  };
}

export function createTableRegistryServiceForTest(): TableRegistryService {
  return createTableRegistryService(createStaticTableRegistryRepository(createPlatformTableDefinitions()));
}

export function createPlatformTableDefinitions(): readonly TableDefinitionDTO[] {
  return [
    table('CommandTransaction', 'transaction', 'ledger', 'transaction-period', [
      'id',
      'commandId',
      'idempotencyKey',
      'status',
      'createdAt',
      'updatedAt',
      'resultJson',
      'errorCode',
    ]),
    table('Session', 'runtime', 'runtime', 'none', [
      'id',
      'schemaVersion',
      'recordVersion',
      'sessionId',
      'tokenFingerprint',
      'userId',
      'authVersion',
      'issuedAt',
      'idleExpiresAt',
      'absoluteExpiresAt',
      'lastSeenAt',
      'revokedAt',
      'status',
    ]),
    table('UserAccount', 'core', 'master', 'none', [
      'id',
      'schemaVersion',
      'recordVersion',
      'userId',
      'loginId',
      'loginIdNormalized',
      'displayName',
      'tenantId',
      'authVersion',
      'disabled',
      'passwordChangeRequired',
      'failedLoginCount',
      'lockedUntil',
      'lastLoginAt',
      'actionsJson',
      'branchIdsJson',
      'warehouseIdsJson',
    ]),
    table('Tenant', 'core', 'master', 'none', [
      'id',
      'schemaVersion',
      'recordVersion',
      'tenantId',
      'displayName',
      'status',
      'timezone',
      'activeConfigVersionId',
    ]),
    table('Branch', 'core', 'master', 'none', [
      'id',
      'schemaVersion',
      'recordVersion',
      'branchId',
      'tenantId',
      'branchCode',
      'name',
      'status',
    ]),
    table('Warehouse', 'core', 'master', 'none', [
      'id',
      'schemaVersion',
      'recordVersion',
      'warehouseId',
      'tenantId',
      'branchId',
      'warehouseCode',
      'name',
      'status',
      'directSaleEnabled',
      'negativeStockPolicy',
      'lotTrackingDefault',
      'serialTrackingDefault',
    ]),
    table('Role', 'core', 'master', 'none', [
      'id',
      'schemaVersion',
      'recordVersion',
      'roleId',
      'tenantId',
      'name',
      'status',
    ]),
    table('RolePermission', 'core', 'master', 'none', ['id', 'roleId', 'action', 'tenantId']),
    table('UserRole', 'core', 'master', 'none', [
      'id',
      'schemaVersion',
      'recordVersion',
      'userRoleId',
      'userId',
      'roleId',
      'status',
    ]),
    table('UserScope', 'core', 'master', 'none', [
      'id',
      'schemaVersion',
      'recordVersion',
      'userScopeId',
      'userId',
      'tenantId',
      'scopeType',
      'scopeId',
      'status',
      'effectiveFrom',
      'effectiveTo',
    ]),
    table('TenantConfigVersion', 'core', 'master', 'none', [
      'id',
      'schemaVersion',
      'recordVersion',
      'configVersionId',
      'tenantId',
      'configType',
      'effectiveFrom',
      'status',
    ]),
    table('SchemaMigration', 'core', 'runtime', 'none', [
      'id',
      'migrationId',
      'tableName',
      'fromVersion',
      'toVersion',
      'status',
      'createdAt',
    ]),
    table('PartitionRegistry', 'core', 'runtime', 'none', [
      'id',
      'schemaVersion',
      'recordVersion',
      'partitionId',
      'storageRole',
      'partitionKey',
      'spreadsheetId',
      'status',
      'activeFrom',
      'closedAt',
      'archivedAt',
      'capacityPct',
      'readOnly',
      'rowCount',
    ]),
    table('ImportBatch', 'runtime', 'runtime', 'none', [
      'id',
      'batchId',
      'importType',
      'schemaVersion',
      'recordVersion',
      'actorId',
      'scopeKey',
      'status',
      'rowCount',
      'validCount',
      'invalidCount',
      'selectionMode',
      'committedAt',
      'sourceFileName',
      'checksum',
    ], 'operations'),
    table('ImportStagingRow', 'runtime', 'runtime', 'none', [
      'id',
      'schemaVersion',
      'recordVersion',
      'rowSetVersion',
      'setIsEmpty',
      'stagingRowId',
      'batchId',
      'rowNumber',
      'rowKey',
      'validationStatus',
      'errorsJson',
      'errorCount',
      'commitStatus',
      'sourceObjectId',
      'payloadJson',
    ], 'operations'),
    table('ExportRun', 'runtime', 'runtime', 'none', [
      'id',
      'schemaVersion',
      'recordVersion',
      'exportRunId',
      'reportId',
      'actorId',
      'scopeFingerprint',
      'status',
      'requestedAt',
      'startedAt',
      'completedAt',
      'expiresAt',
      'fileId',
      'rowCount',
      'runId',
      'queryJson',
    ], 'operations'),
    table('BackgroundRun', 'runtime', 'runtime', 'none', [
      'id',
      'schemaVersion',
      'recordVersion',
      'runId',
      'jobType',
      'status',
      'attempt',
      'leaseUntil',
      'checkpointKey',
      'startedAt',
      'endedAt',
      'errorCode',
    ], 'operations'),
    table('HealthCheck', 'runtime', 'runtime', 'none', [
      'id',
      'schemaVersion',
      'recordVersion',
      'checkId',
      'checkType',
      'status',
      'observedAt',
      'resourceKey',
      'threshold',
      'observedValue',
      'message',
      'acknowledgedAt',
    ], 'operations'),
    table('CapacityAlert', 'runtime', 'runtime', 'none', [
      'id',
      'schemaVersion',
      'recordVersion',
      'alertId',
      'alertType',
      'status',
      'observedAt',
      'resourceKey',
      'threshold',
      'observedValue',
      'acknowledgedAt',
    ], 'operations'),
    table('RuntimeRecord', 'runtime', 'runtime', 'none', [
      'id',
      'schemaVersion',
      'recordVersion',
      'runtimeSetVersion',
      'setIsEmpty',
      'runtimeScope',
      'recordId',
      'recordType',
      'expiresAt',
      'evidence',
    ], 'operations'),
    table('AttachmentMetadata', 'transaction', 'document', 'transaction-period', [
      'id',
      'schemaVersion',
      'recordVersion',
      'attachmentId',
      'partitionKey',
      'objectType',
      'objectId',
      'branchId',
      'warehouseId',
      'driveFileId',
      'fileName',
      'mimeType',
      'sizeBytes',
      'checksum',
      'status',
      'uploadedBy',
      'uploadedAt',
      'deletedAt',
    ], 'operations'),
    table('BackupRun', 'transaction', 'document', 'transaction-period', [
      'id',
      'schemaVersion',
      'recordVersion',
      'backupSetVersion',
      'backupRetention',
      'backupRunId',
      'status',
      'backupType',
      'requestedBy',
      'requestedAt',
      'startedAt',
      'completedAt',
      'manifestFileId',
      'appVersion',
      'checksum',
      'retentionUntil',
      'manifestJson',
    ], 'operations'),
    table('RestoreRun', 'transaction', 'document', 'transaction-period', [
      'id',
      'schemaVersion',
      'recordVersion',
      'restoreRunId',
      'backupRunId',
      'status',
      'requestedBy',
      'preparedAt',
      'switchedAt',
      'oldConfigVersion',
      'newConfigVersion',
      'healthResult',
      'writeFrozen',
    ], 'operations'),
    table('ReportProjectionState', 'transaction', 'projection', 'transaction-period', [
      'projectionId',
      'reportId',
      'branchId',
      'warehouseId',
      'dateBucket',
      'asOf',
      'sourcePartitionKey',
      'buildVersion',
      'status',
    ], 'reporting'),
    table('DashboardProjection', 'transaction', 'projection', 'transaction-period', [
      'id',
      'tenantId',
      'schemaVersion',
      'recordVersion',
      'projectionKey',
      'branchId',
      'warehouseId',
      'dateBucket',
      'responseJson',
    ], 'reporting'),
    table('ReportRow', 'transaction', 'projection', 'transaction-period', [
      'id',
      'schemaVersion',
      'recordVersion',
      'rowSetVersion',
      'setIsEmpty',
      'reportId',
      'rowIndex',
      'rowJson',
    ], 'reporting'),
    table('ReportingExportRun', 'transaction', 'runtime', 'transaction-period', [
      'id',
      'tenantId',
      'schemaVersion',
      'recordVersion',
      'runId',
      'requestedBy',
      'status',
      'format',
      'queryJson',
      'requestedAt',
      'completedAt',
      'rowCount',
      'fileId',
      'routing',
    ], 'reporting'),
    table('Product', 'core', 'master', 'none', [
      'id',
      'tenantId',
      'schemaVersion',
      'recordVersion',
      'productId',
      'productCode',
      'name',
      'productType',
      'categoryId',
      'brandId',
      'taxCode',
      'isActive',
      'descriptionJson',
    ], 'catalog'),
    table('Variant', 'core', 'master', 'none', [
      'id',
      'tenantId',
      'schemaVersion',
      'recordVersion',
      'variantId',
      'productId',
      'sku',
      'skuNormalized',
      'displayName',
      'inventoryMode',
      'lotTracking',
      'serialTracking',
      'defaultUnitId',
      'isActive',
      'unitPriceVnd',
    ], 'catalog'),
    table('VariantBarcode', 'core', 'master', 'none', [
      'id',
      'tenantId',
      'schemaVersion',
      'recordVersion',
      'barcodeId',
      'variantId',
      'unitVersionId',
      'barcode',
      'barcodeNormalized',
      'barcodeKind',
      'isActive',
    ], 'catalog'),
    table('UnitConversionVersion', 'core', 'master', 'none', [
      'id',
      'tenantId',
      'schemaVersion',
      'recordVersion',
      'unitVersionId',
      'variantId',
      'unitId',
      'unitName',
      'baseUnitId',
      'factor',
      'saleEnabled',
      'purchaseEnabled',
      'effectiveFrom',
      'effectiveTo',
      'isActive',
    ], 'catalog'),
    table('PriceList', 'core', 'master', 'none', [
      'priceListId',
      'name',
      'scopeType',
      'branchId',
      'customerGroupId',
      'status',
      'effectiveFrom',
      'effectiveTo',
      'priority',
    ], 'catalog'),
    table('PriceRule', 'core', 'master', 'none', [
      'priceRuleId',
      'priceListId',
      'variantId',
      'unitVersionId',
      'unitPriceVnd',
      'effectiveFrom',
      'effectiveTo',
      'priority',
      'status',
    ], 'catalog'),
    table('Promotion', 'core', 'master', 'none', [
      'promotionId',
      'name',
      'promotionType',
      'status',
      'branchScopeKey',
      'effectiveFrom',
      'effectiveTo',
      'priority',
      'usageLimit',
      'budgetVnd',
      'detailsJson',
    ], 'catalog'),
    table('Voucher', 'core', 'master', 'none', [
      'voucherId',
      'promotionId',
      'codeNormalized',
      'status',
      'effectiveFrom',
      'effectiveTo',
      'usageLimit',
      'usedCount',
      'detailsJson',
    ], 'catalog'),
    table('Customer', 'core', 'master', 'none', [
      'id',
      'tenantId',
      'schemaVersion',
      'recordVersion',
      'customerId',
      'customerCode',
      'displayName',
      'phone',
      'phoneNormalized',
      'email',
      'emailNormalized',
      'customerGroupId',
      'status',
      'mergedIntoCustomerId',
      'detailsJson',
    ], 'crm'),
    table('CustomerGroup', 'core', 'master', 'none', [
      'customerGroupId',
      'name',
      'assignmentMode',
      'status',
      'priority',
      'detailsJson',
    ], 'crm'),
    table('SaleOrder', 'transaction', 'document', 'transaction-period', [
      'id',
      'tenantId',
      'schemaVersion',
      'recordVersion',
      'saleOrderId',
      'partitionKey',
      'businessNumber',
      'source',
      'branchId',
      'warehouseId',
      'status',
      'paymentStatus',
      'customerId',
      'cashierId',
      'salesPersonId',
      'note',
      'subtotalVnd',
      'discountVnd',
      'taxVnd',
      'shippingFeeVnd',
      'totalVnd',
      'paidVnd',
      'receivableVnd',
      'quoteVersion',
      'draftVersion',
      'createdAt',
      'updatedAt',
      'completedAt',
      'confirmedAt',
      'packingAt',
      'shippedAt',
      'deliveredAt',
      'cancelledAt',
      'linkedReturnId',
      'linkedExchangeSaleId',
      'recipientJson',
      'snapshotJson',
    ], 'sales'),
    table('SaleOrderLine', 'transaction', 'document', 'transaction-period', [
      'id',
      'tenantId',
      'schemaVersion',
      'recordVersion',
      'lineSetVersion',
      'setIsEmpty',
      'saleOrderLineId',
      'saleOrderId',
      'lineId',
      'variantId',
      'unitVersionId',
      'quantity',
      'quantityMilli',
      'unitPriceVnd',
      'lineDiscountVnd',
      'sku',
      'displayName',
      'unitName',
      'lineSubtotalVnd',
      'lineTotalVnd',
      'costVnd',
      'lotId',
      'serialId',
      'note',
      'snapshotJson',
    ], 'sales'),
    table('SaleTenderDraft', 'transaction', 'document', 'transaction-period', [
      'id',
      'tenantId',
      'schemaVersion',
      'recordVersion',
      'tenderSetVersion',
      'setIsEmpty',
      'tenderDraftId',
      'tenderId',
      'saleOrderId',
      'methodId',
      'paymentMethodId',
      'amountVnd',
      'cashDrawerId',
      'snapshotJson',
    ], 'sales'),
    table('ReceiptSnapshot', 'transaction', 'document', 'transaction-period', [
      'id',
      'tenantId',
      'schemaVersion',
      'recordVersion',
      'receiptId',
      'saleOrderId',
      'businessNumber',
      'renderVersion',
      'receiptFormat',
      'createdAt',
      'branchId',
      'warehouseId',
      'cashierId',
      'customerId',
      'linesJson',
      'totalsJson',
      'snapshotJson',
    ], 'sales'),
    table('SaleReturn', 'transaction', 'document', 'transaction-period', [
      'id',
      'tenantId',
      'schemaVersion',
      'recordVersion',
      'returnId',
      'partitionKey',
      'branchId',
      'warehouseId',
      'customerId',
      'sourceSaleOrderId',
      'status',
      'returnType',
      'reason',
      'receivedAt',
      'resolvedAt',
      'actorId',
      'approvedBy',
      'linkedExchangeSaleId',
      'snapshotJson',
    ], 'sales'),
    table('SaleReturnLine', 'transaction', 'document', 'transaction-period', [
      'id',
      'tenantId',
      'schemaVersion',
      'recordVersion',
      'lineSetVersion',
      'setIsEmpty',
      'returnLineId',
      'returnId',
      'sourceSaleLineId',
      'variantId',
      'quantity',
      'quantityMilli',
      'disposition',
      'refundVnd',
      'unitCostVnd',
      'serialId',
      'lotId',
      'note',
      'snapshotJson',
    ], 'sales'),
    table('WarrantyCase', 'transaction', 'document', 'transaction-period', [
      'id',
      'tenantId',
      'schemaVersion',
      'recordVersion',
      'warrantyCaseId',
      'customerId',
      'saleOrderId',
      'saleLineId',
      'variantId',
      'serialId',
      'policyVersionId',
      'receivedAt',
      'status',
      'issue',
      'resolution',
      'attachmentIdsJson',
    ], 'sales'),
    table('InventoryMovement', 'transaction', 'ledger', 'transaction-period', [
      'id',
      'tenantId',
      'schemaVersion',
      'movementId',
      'partitionKey',
      'movementType',
      'warehouseId',
      'variantId',
      'lotId',
      'serialId',
      'quantityMilli',
      'unitVersionId',
      'unitCostVnd',
      'totalCostVnd',
      'sourceType',
      'sourceId',
      'sourceLineId',
      'effectiveAt',
      'actorId',
      'approverId',
      'idempotencyKey',
      'reversalOfMovementId',
      'requiresCostReconciliation',
      'snapshotJson',
    ], 'inventory'),
    table('InventoryBalance', 'transaction', 'projection', 'none', [
      'id',
      'tenantId',
      'schemaVersion',
      'recordVersion',
      'balanceId',
      'warehouseId',
      'variantId',
      'onHandMilli',
      'availableMilli',
      'reservedMilli',
      'inTransitMilli',
      'quarantineMilli',
      'inventoryValueVnd',
      'asOfMovementId',
      'reconciliationJson',
    ], 'inventory'),
    table('InventoryLotBalance', 'transaction', 'projection', 'none', [
      'lotBalanceId',
      'warehouseId',
      'variantId',
      'lotCode',
      'expiryDate',
      'onHandMilli',
      'availableMilli',
      'quarantineMilli',
      'metadataJson',
    ], 'inventory'),
    table('SerialState', 'transaction', 'projection', 'none', [
      'serialId',
      'variantId',
      'warehouseId',
      'status',
      'sourceMovementId',
      'sourceSaleLineId',
      'updatedAt',
      'historyJson',
    ], 'inventory'),
    table('StockTransfer', 'transaction', 'document', 'transaction-period', [
      'transferId',
      'sourceWarehouseId',
      'destinationWarehouseId',
      'status',
      'createdAt',
      'approvedAt',
      'shippedAt',
      'receivedAt',
      'reasonJson',
    ], 'inventory'),
    table('StockTransferLine', 'transaction', 'document', 'transaction-period', [
      'transferLineId',
      'transferId',
      'variantId',
      'quantityMilli',
      'receivedQuantityMilli',
      'varianceJson',
    ], 'inventory'),
    table('StocktakeSession', 'transaction', 'document', 'transaction-period', [
      'sessionId',
      'warehouseId',
      'status',
      'snapshotAt',
      'submittedAt',
      'approvedAt',
      'scopeJson',
    ], 'inventory'),
    table('StocktakeLine', 'transaction', 'document', 'transaction-period', [
      'stocktakeLineId',
      'sessionId',
      'variantId',
      'lotId',
      'serialId',
      'snapshotQuantityMilli',
      'countedQuantityMilli',
      'varianceMilli',
      'reasonJson',
    ], 'inventory'),
    table('Supplier', 'core', 'master', 'none', [
      'id',
      'tenantId',
      'schemaVersion',
      'recordVersion',
      'supplierId',
      'supplierCode',
      'name',
      'taxCode',
      'status',
      'paymentTermsJson',
      'contactJson',
      'note',
      'createdAt',
      'updatedAt',
    ], 'purchasing'),
    table('PurchaseOrder', 'transaction', 'document', 'transaction-period', [
      'id',
      'tenantId',
      'schemaVersion',
      'recordVersion',
      'purchaseOrderId',
      'partitionKey',
      'businessNumber',
      'supplierId',
      'branchId',
      'warehouseId',
      'status',
      'expectedDate',
      'termsSnapshotJson',
      'attachmentIdsJson',
      'subtotalVnd',
      'discountVnd',
      'vatVnd',
      'totalVnd',
      'note',
      'createdAt',
      'updatedAt',
      'submittedAt',
      'approvedAt',
      'cancelledAt',
    ], 'purchasing'),
    table('PurchaseOrderLine', 'transaction', 'document', 'transaction-period', [
      'id',
      'schemaVersion',
      'recordVersion',
      'lineSetVersion',
      'setIsEmpty',
      'purchaseOrderLineId',
      'purchaseOrderId',
      'lineId',
      'variantId',
      'unitVersionId',
      'quantity',
      'quantityMilli',
      'unitCostVnd',
      'lineDiscountVnd',
      'vatVnd',
      'note',
      'receivedQuantityMilli',
      'lineSubtotalVnd',
      'lineTotalVnd',
    ], 'purchasing'),
    table('GoodsReceipt', 'transaction', 'document', 'transaction-period', [
      'id',
      'tenantId',
      'schemaVersion',
      'recordVersion',
      'goodsReceiptId',
      'partitionKey',
      'businessNumber',
      'supplierId',
      'purchaseOrderId',
      'branchId',
      'warehouseId',
      'status',
      'receivedDate',
      'subtotalVnd',
      'discountVnd',
      'vatVnd',
      'landedCostVnd',
      'totalPayableVnd',
      'actorId',
      'approvedBy',
      'createdAt',
      'updatedAt',
      'approvedAt',
    ], 'purchasing'),
    table('GoodsReceiptLine', 'transaction', 'document', 'transaction-period', [
      'id',
      'schemaVersion',
      'recordVersion',
      'lineSetVersion',
      'setIsEmpty',
      'goodsReceiptLineId',
      'goodsReceiptId',
      'lineId',
      'purchaseOrderLineId',
      'variantId',
      'unitVersionId',
      'quantity',
      'quantityMilli',
      'unitCostVnd',
      'lineDiscountVnd',
      'vatVnd',
      'allocatedLandedCostVnd',
      'lotId',
      'serialIdsJson',
      'note',
      'lineSubtotalVnd',
      'lineTotalVnd',
      'actualCostVnd',
      'returnedQuantityMilli',
    ], 'purchasing'),
    table('LandedCostAdjustment', 'transaction', 'document', 'transaction-period', [
      'id',
      'tenantId',
      'schemaVersion',
      'recordVersion',
      'adjustmentId',
      'partitionKey',
      'goodsReceiptId',
      'adjustmentType',
      'status',
      'method',
      'totalCostVnd',
      'onHandAllocatedVnd',
      'varianceVnd',
      'approvedBy',
      'createdAt',
    ], 'purchasing'),
    table('PurchaseCostVariance', 'transaction', 'ledger', 'transaction-period', [
      'id',
      'tenantId',
      'schemaVersion',
      'varianceId',
      'partitionKey',
      'adjustmentId',
      'goodsReceiptId',
      'goodsReceiptLineId',
      'variantId',
      'warehouseId',
      'amountVnd',
      'effectiveAt',
    ], 'purchasing'),
    table('SupplierReturn', 'transaction', 'document', 'transaction-period', [
      'id',
      'tenantId',
      'schemaVersion',
      'recordVersion',
      'supplierReturnId',
      'partitionKey',
      'supplierId',
      'goodsReceiptId',
      'branchId',
      'warehouseId',
      'status',
      'treatment',
      'reason',
      'actorId',
      'approvedBy',
      'totalVnd',
      'createdAt',
      'updatedAt',
      'approvedAt',
    ], 'purchasing'),
    table('SupplierReturnLine', 'transaction', 'document', 'transaction-period', [
      'id',
      'schemaVersion',
      'recordVersion',
      'lineSetVersion',
      'setIsEmpty',
      'supplierReturnLineId',
      'supplierReturnId',
      'lineId',
      'goodsReceiptLineId',
      'variantId',
      'quantity',
      'quantityMilli',
      'unitCostVnd',
      'note',
      'lineTotalVnd',
    ], 'purchasing'),
    table('CashDrawer', 'core', 'master', 'none', [
      'id',
      'tenantId',
      'schemaVersion',
      'recordVersion',
      'cashDrawerId',
      'branchId',
      'drawerCode',
      'name',
      'drawerType',
      'status',
      'configJson',
    ], 'finance'),
    table('PaymentMethod', 'core', 'master', 'none', [
      'id',
      'tenantId',
      'schemaVersion',
      'recordVersion',
      'paymentMethodId',
      'methodCode',
      'name',
      'methodType',
      'status',
      'configJson',
    ], 'finance'),
    table('Payment', 'transaction', 'document', 'transaction-period', [
      'id',
      'tenantId',
      'schemaVersion',
      'recordVersion',
      'paymentId',
      'partitionKey',
      'branchId',
      'cashDrawerId',
      'payerType',
      'payerId',
      'sourceType',
      'sourceId',
      'sourceLineId',
      'amountVnd',
      'paymentMethodId',
      'status',
      'effectiveAt',
      'shiftId',
      'reversalOfPaymentId',
      'snapshotJson',
    ], 'finance'),
    table('CashTransaction', 'transaction', 'ledger', 'transaction-period', [
      'id',
      'tenantId',
      'schemaVersion',
      'cashTransactionId',
      'partitionKey',
      'branchId',
      'cashDrawerId',
      'transactionType',
      'amountVnd',
      'effectiveAt',
      'paymentId',
      'sourceType',
      'sourceId',
      'sourceLineId',
      'actorId',
      'approverId',
      'shiftId',
      'reversalOfCashTransactionId',
      'idempotencyKey',
      'reasonJson',
    ], 'finance'),
    table('ReceivableLedger', 'transaction', 'ledger', 'transaction-period', [
      'id',
      'tenantId',
      'schemaVersion',
      'recordVersion',
      'obligationId',
      'partitionKey',
      'branchId',
      'customerId',
      'sourceType',
      'sourceId',
      'sourceLineId',
      'dueDate',
      'originalAmountVnd',
      'allocatedAmountVnd',
      'remainingAmountVnd',
      'status',
      'reversalOfObligationId',
      'termsJson',
    ], 'finance'),
    table('PayableLedger', 'transaction', 'ledger', 'transaction-period', [
      'id',
      'tenantId',
      'schemaVersion',
      'recordVersion',
      'obligationId',
      'partitionKey',
      'branchId',
      'supplierId',
      'sourceType',
      'sourceId',
      'sourceLineId',
      'dueDate',
      'originalAmountVnd',
      'allocatedAmountVnd',
      'remainingAmountVnd',
      'status',
      'reversalOfObligationId',
      'termsJson',
    ], 'finance'),
    table('PaymentAllocation', 'transaction', 'ledger', 'transaction-period', [
      'id',
      'tenantId',
      'schemaVersion',
      'allocationId',
      'partitionKey',
      'paymentId',
      'obligationId',
      'amountVnd',
      'allocatedAt',
      'reversalOfAllocationId',
      'reasonJson',
    ], 'finance'),
    table('CustomerCredit', 'transaction', 'ledger', 'transaction-period', [
      'id',
      'tenantId',
      'schemaVersion',
      'recordVersion',
      'creditId',
      'partitionKey',
      'branchId',
      'customerId',
      'sourcePaymentId',
      'sourceType',
      'sourceId',
      'sourceLineId',
      'amountVnd',
      'consumedAmountVnd',
      'status',
      'snapshotJson',
    ], 'finance'),
    table('SupplierPrepayment', 'transaction', 'ledger', 'transaction-period', [
      'id',
      'tenantId',
      'schemaVersion',
      'recordVersion',
      'prepaymentId',
      'partitionKey',
      'branchId',
      'supplierId',
      'sourcePaymentId',
      'sourceType',
      'sourceId',
      'sourceLineId',
      'amountVnd',
      'consumedAmountVnd',
      'status',
      'snapshotJson',
    ], 'finance'),
    table('Shift', 'transaction', 'document', 'transaction-period', [
      'id',
      'tenantId',
      'schemaVersion',
      'recordVersion',
      'shiftId',
      'partitionKey',
      'branchId',
      'cashDrawerId',
      'warehouseId',
      'cashierId',
      'status',
      'openedAt',
      'submittedAt',
      'closedAt',
      'lockedAt',
      'openingCashVnd',
      'expectedCashVnd',
      'actualCashVnd',
      'varianceVnd',
      'closeReason',
      'approverId',
      'breakdownJson',
    ], 'finance'),
    table('Expense', 'transaction', 'document', 'transaction-period', [
      'expenseId',
      'partitionKey',
      'branchId',
      'categoryId',
      'cashDrawerId',
      'payee',
      'amountVnd',
      'effectiveAt',
      'status',
      'cashTransactionId',
      'actorId',
      'approverId',
      'attachmentJson',
    ], 'finance'),
  ];
}

function table(
  tableName: string,
  storageRole: TableDefinitionDTO['storageRole'],
  lifecycle: TableDefinitionDTO['lifecycle'],
  partitionPolicy: TableDefinitionDTO['partitionPolicy'],
  headers: readonly string[],
  owner: TableDefinitionDTO['owner'] = 'platform',
): TableDefinitionDTO {
  return {
    tableName,
    owner,
    storageRole,
    sheetName: tableName,
    lifecycle,
    schemaVersion: 1,
    primaryKey: 'id',
    headers: headers.map((name) => ({
      name,
      type: resolveColumnType(name),
      required: !optionalColumnNames.has(name),
    })),
    partitionPolicy,
    lookupKeys: [{ name: `${tableName}.primary`, columns: ['id'], unique: true }],
  };
}

const optionalColumnNames = new Set([
  'revokedAt',
  'closedAt',
  'effectiveTo',
  'resultJson',
  'errorCode',
  'spreadsheetId',
  'closedAt',
  'archivedAt',
  'selectionMode',
  'committedAt',
  'sourceFileName',
  'checksum',
  'errorsJson',
  'sourceObjectId',
  'payloadJson',
  'startedAt',
  'completedAt',
  'expiresAt',
  'fileId',
  'runId',
  'queryJson',
  'checkpointKey',
  'endedAt',
  'threshold',
  'observedValue',
  'message',
  'acknowledgedAt',
  'branchId',
  'warehouseId',
  'deletedAt',
  'backupRetention',
  'backupType',
  'requestedAt',
  'manifestFileId',
  'appVersion',
  'retentionUntil',
  'manifestJson',
  'switchedAt',
  'newConfigVersion',
  'healthResult',
  'categoryId',
  'brandId',
  'taxCode',
  'descriptionJson',
  'paymentTermsJson',
  'contactJson',
  'projectionKey',
  'responseJson',
  'rowJson',
  'expectedDate',
  'termsSnapshotJson',
  'attachmentIdsJson',
  'submittedAt',
  'purchaseOrderId',
  'allocatedLandedCostVnd',
  'serialIdsJson',
  'customerId',
  'salesPersonId',
  'note',
  'quoteVersion',
  'completedAt',
  'confirmedAt',
  'packingAt',
  'shippedAt',
  'deliveredAt',
  'cancelledAt',
  'linkedReturnId',
  'linkedExchangeSaleId',
  'recipientJson',
  'setIsEmpty',
  'methodId',
  'paymentMethodId',
  'cashDrawerId',
  'linesJson',
  'totalsJson',
  'sourceSaleOrderId',
  'resolvedAt',
  'approvedBy',
  'sourceSaleLineId',
  'policyVersionId',
  'resolution',
  'attachmentIdsJson',
  'sku',
  'costVnd',
  'lotId',
  'serialId',
  'unitVersionId',
  'sourceLineId',
  'approverId',
  'reversalOfMovementId',
  'requiresCostReconciliation',
  'snapshotJson',
  'asOfMovementId',
  'reconciliationJson',
  'actualCashVnd',
  'varianceVnd',
  'closeReason',
]);

function resolveColumnType(name: string): TableDefinitionDTO['headers'][number]['type'] {
  if (name.endsWith('Json')) return 'json';
  if (name.endsWith('At') || name === 'effectiveFrom' || name === 'effectiveTo') return 'timestamp';
  if (
    name === 'schemaVersion' ||
    name === 'recordVersion' ||
    name === 'draftVersion' ||
    name === 'lineSetVersion' ||
    name === 'tenderSetVersion' ||
    name === 'rowSetVersion' ||
    name === 'backupSetVersion' ||
    name === 'runtimeSetVersion' ||
    name === 'rowIndex' ||
    name === 'renderVersion' ||
    name === 'quantity' ||
    name === 'attempt' ||
    name === 'capacityPct' ||
    name === 'factor' ||
    name === 'priority' ||
    name === 'usageLimit' ||
    name === 'usedCount' ||
    name === 'rowCount' ||
    name === 'validCount' ||
    name === 'invalidCount' ||
    name === 'errorCount' ||
    name.endsWith('Vnd') ||
    name.endsWith('Milli') ||
    name.endsWith('Days') ||
    name.endsWith('Bytes')
  ) {
    return 'integer';
  }
  if (
    name.startsWith('is') ||
    name.startsWith('has') ||
    name.startsWith('requires') ||
    name.endsWith('Enabled') ||
    name.endsWith('Tracking') ||
    name === 'readOnly' ||
    name === 'evidence' ||
    name === 'setIsEmpty' ||
    name === 'writeFrozen' ||
    name === 'saleEnabled' ||
    name === 'purchaseEnabled' ||
    name === 'directSaleEnabled'
  ) {
    return 'boolean';
  }
  return 'string';
}

function findDefinition(
  repository: TableRegistryRepository,
  tableName: string,
): TableDefinitionDTO {
  const definition = repository.listDefinitions().find((candidate) => candidate.tableName === tableName);

  if (definition === undefined) {
    throw new Error(`Unknown table: ${tableName}`);
  }

  return definition;
}
