export const apiErrorCodes = [
  'INVALID_REQUEST',
  'INVALID_INPUT',
  'OPERATION_NOT_SUPPORTED',
  'SESSION_REQUIRED',
  'SESSION_EXPIRED',
  'INVALID_CREDENTIALS',
  'AUTH_LOCKED',
  'PERMISSION_DENIED',
  'SCOPE_DENIED',
  'COMMAND_REQUIRED',
  'COMMAND_ALREADY_COMMITTED',
  'COMMAND_PENDING',
  'VERSION_CONFLICT',
  'DUPLICATE_SKU',
  'DUPLICATE_BARCODE',
  'EFFECTIVE_RANGE_CONFLICT',
  'PRODUCT_INACTIVE',
  'PRICE_CHANGED',
  'PROMOTION_CHANGED',
  'VOUCHER_UNAVAILABLE',
  'POINT_BALANCE_CHANGED',
  'INSUFFICIENT_STOCK',
  'SERIAL_REQUIRED',
  'LOT_REQUIRED',
  'TEMPORARY_COST_REQUIRED',
  'SHIFT_ALREADY_OPEN',
  'SHIFT_NOT_OPEN',
  'SHIFT_VARIANCE_REASON_REQUIRED',
  'PAYMENT_ALLOCATION_EXCEEDS_AMOUNT',
  'OBLIGATION_ALLOCATION_EXCEEDS_BALANCE',
  'PAYMENT_REVERSAL_EXCEEDS_ORIGINAL',
  'DUPLICATE_SUPPLIER_CODE',
  'SUPPLIER_DISABLED',
  'PURCHASE_ORDER_STATE_INVALID',
  'GOODS_RECEIPT_STATE_INVALID',
  'SUPPLIER_RETURN_STATE_INVALID',
  'PURCHASE_RECEIPT_LIMIT_EXCEEDED',
  'LANDED_COST_ALLOCATION_MISMATCH',
  'LOCK_TIMEOUT',
  'TRANSPORT_ERROR',
  'INTERNAL_ERROR',
] as const;

export type ApiErrorCode = (typeof apiErrorCodes)[number];

export interface ApiError {
  code: ApiErrorCode;
  message: string;
  details?: Record<string, string>;
}
